scripts:
  dev:
    cmd: 'deno run src/app.ts'
    desc: 'run app.ts file'
    allow: ['env', 'net', 'read', 'write', 'plugin']
    unstable: true
  lint:
    cmd: 'deno lint src/'
    desc: 'lint all ts file'
    unstable: true
  fmt:
    cmd: 'deno fmt src/'
    desc: 'format all ts file'

watcher:
  exts: ['js', 'jsx', 'ts', 'tsx', 'json']
  skip: ['*/.git/*']
