name: gh-pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README*'
      - '.vscode/*'

env:
  node-version: '14'
  deploy-dir: './__sapper__/export'

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - run: npm i --save
      - run: npm run export
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}
