name: gh-pages

on:
  push:
    paths:
      - 'src'

env:
  node-version: '14'

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - run: npm i --save
      - run: npm run lint
