name: test

on:
  push:
    paths:
      - src
      - package.json
      - package-lock.json
      - tsconfig.json
      - webpack.config.json
      - Dockerfile
      - docker-compose.yml
      - .eslintrc.json
      - '.github/workflows'

env:
  node-version: '14'
  DOCKER_BUILDKIT: 1

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  setup:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - run: npm i --save

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: lint # test
    steps:
      - run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        service:
          - builder
          - devenv
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose pull ${{ matrix.service }}
      - run: docker-compose build ${{ matrix.service }}
